runtime: php82
service: api
entrypoint: serve public/index.php
handlers:
  - url: /.*
    script: auto
    secure: always
env_variables:
  APP_ENV: production
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  APP_SERVICES_CACHE: /tmp/services.php
  APP_PACKAGES_CACHE: /tmp/packages.php
  APP_CONFIG_CACHE: /tmp/config.php
  APP_ROUTES_CACHE: /tmp/routes.php
  CACHE_DRIVER: database
  SESSION_DRIVER: database
